Vue.component('pane',{
    name:'pane',
    template:`
        <div class="pane" v-show="show" :class="className">
            <slot></slot>
        </div>
    `,
    /*template:'\
        <div class="pane" v-show="show">\
            <slot></slot>\
        </div>',*/
    props:{
        name:{
            type:String
        },
        label:{
            type:String,
            default:''
        },
        closeable:{
            type:Boolean,
            default: false
        }
    },
    data:function(){
        return{
            show:true,
            className:{
                'currentPrevious':false,
                'currentNext':false,
                'next':false,
                'previous':false
            }
        }
    },
    methods:{
        updateNav(){
            this.$parent.updateNav();
        }
    },
    watch:{
        label:function(){
            this.updateNav();
        },
        name:function(){
            this.updateNav();
        }
    },
    mounted(){
        this.updateNav();
    }
});